# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8

pipelines:
  branches:
    develop:
      - step:
          script:
            - cd client
            - yarn install
            - yarn build --prod --aot=false --buildOptimizer=false
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
            - aws s3 rm s3://brookfield.venturplex.com --recursive
            - aws s3 cp ./dist/apps/portal s3://brookfield.venturplex.com/ --recursive --acl public-read --cache-control max-age=0
            - cd ..
      - step:
          script:
            - cd backend
            - npm install
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awsebcli --upgrade
            - eb init Brookfield -r us-west-2 -p docker
            - eb deploy Brookfield-dev-env --timeout 20
    master:
      - step:
          script:
            - yarn install
            - yarn build
            - yarn deploy:prod
