# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8

pipelines:
  branches:
    feat/backend:
      - step:
          script:
            - cd backend
            - npm install
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awsebcli --upgrade
            - eb init busykid -r us-west-2 -p docker
            - eb deploy Brookfield-dev-env --timeout 20
    develop:
      - step:
          script:
            - cd client
            - yarn install
            - yarn build
            - yarn deploy:dev
    master:
      - step:
          script:
            - yarn install
            - yarn build
            - yarn deploy:prod
